org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=depillage
mod.name=Depillage
mod.group=me.pajic
mod.version=1.0.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Kill enough pillagers at an outpost to stop them from spawning
mod.sources_url=https://github.com/pajicadvance/depillage
mod.homepage_url=https://modrinth.com/mod/depillage
mod.issues_url=https://github.com/pajicadvance/depillage/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.mixson=[VERSIONED]

publish.modrinth=3kSqA1Re
publish.curseforge=1555926
publish.github=false
